# Basic example

In [1]:
import numpy as np
from sklearn import neighbors, datasets, preprocessing
from sklearn.model_selection import train_test_split

In [2]:
iris = datasets.load_iris()
X, y = iris.data[:, :2], iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=33)

scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

## kNN

In [3]:
knn = neighbors.KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

In [4]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy_score:", accuracy_score(y_test, y_pred))
print("classification_report:\n", classification_report(y_test, y_pred))
print("confusion_matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy_score: 0.631578947368
classification_report:
              precision    recall  f1-score   support

          0       1.00      1.00      1.00         8
          1       0.42      0.73      0.53        11
          2       0.73      0.42      0.53        19

avg / total       0.70      0.63      0.63        38

confusion_matrix:
 [[ 8  0  0]
 [ 0  8  3]
 [ 0 11  8]]


In [5]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("mean_absolute_error:", mean_absolute_error(y_test, y_pred))
print("Mean_squared_error", mean_squared_error(y_test, y_pred))
print("r2_score:", r2_score(y_test, y_pred))

mean_absolute_error: 0.368421052632
Mean_squared_error 0.368421052632
r2_score: 0.412154696133


In [6]:
from sklearn.metrics import adjusted_rand_score, homogeneity_score, v_measure_score

print("adjusted_rand_score:", adjusted_rand_score(y_test, y_pred))
print("homogeneity_score", homogeneity_score(y_test, y_pred))
print("v_measure_score:", v_measure_score(y_test, y_pred))

adjusted_rand_score: 0.309611910983
homogeneity_score 0.50657823472
v_measure_score: 0.50657823472


## Linear regression

In [7]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression(normalize=True)
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

# R^2 method
lr.score(X_test, y_test)

0.55626655930805857

In [8]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("Mean_absolute_error:", mean_absolute_error(y_test, y_pred))
print("Mean_squared_error", mean_squared_error(y_test, y_pred))
print("r2_score:", r2_score(y_test, y_pred))

Mean_absolute_error: 0.436537055729
Mean_squared_error 0.278101636999
r2_score: 0.556266559308


In [9]:
from sklearn.metrics import adjusted_rand_score, homogeneity_score, v_measure_score

print("adjusted_rand_score:", adjusted_rand_score(y_test, y_pred))
print("homogeneity_score", homogeneity_score(y_test, y_pred))
print("v_measure_score:", v_measure_score(y_test, y_pred))

adjusted_rand_score: 0.00151500804848
homogeneity_score 0.916075718855
v_measure_score: 0.419709760602


## Naive bayes

In [10]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy_score:", accuracy_score(y_test, y_pred))
print("classification_report:\n", classification_report(y_test, y_pred))
print("confusion_matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy_score: 0.710526315789
classification_report:
              precision    recall  f1-score   support

          0       1.00      1.00      1.00         8
          1       0.50      0.64      0.56        11
          2       0.75      0.63      0.69        19

avg / total       0.73      0.71      0.72        38

confusion_matrix:
 [[ 8  0  0]
 [ 0  7  4]
 [ 0  7 12]]


In [12]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("mean_absolute_error:", mean_absolute_error(y_test, y_pred))
print("Mean_squared_error", mean_squared_error(y_test, y_pred))
print("r2_score:", r2_score(y_test, y_pred))

mean_absolute_error: 0.289473684211
Mean_squared_error 0.289473684211
r2_score: 0.538121546961


In [13]:
from sklearn.metrics import adjusted_rand_score, homogeneity_score, v_measure_score

print("adjusted_rand_score:", adjusted_rand_score(y_test, y_pred))
print("homogeneity_score", homogeneity_score(y_test, y_pred))
print("v_measure_score:", v_measure_score(y_test, y_pred))

adjusted_rand_score: 0.347475429348
homogeneity_score 0.523792125581
v_measure_score: 0.517122818967


## SVM

In [14]:
from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)

svc.score(X_test, y_test)

0.71052631578947367

In [15]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy_score:", accuracy_score(y_test, y_pred))
print("classification_report:\n", classification_report(y_test, y_pred))
print("confusion_matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy_score: 0.710526315789
classification_report:
              precision    recall  f1-score   support

          0       1.00      1.00      1.00         8
          1       0.50      0.64      0.56        11
          2       0.75      0.63      0.69        19

avg / total       0.73      0.71      0.72        38

confusion_matrix:
 [[ 8  0  0]
 [ 0  7  4]
 [ 0  7 12]]


In [16]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("mean_absolute_error:", mean_absolute_error(y_test, y_pred))
print("Mean_squared_error", mean_squared_error(y_test, y_pred))
print("r2_score:", r2_score(y_test, y_pred))

mean_absolute_error: 0.289473684211
Mean_squared_error 0.289473684211
r2_score: 0.538121546961


In [17]:
from sklearn.metrics import adjusted_rand_score, homogeneity_score, v_measure_score

print("adjusted_rand_score:", adjusted_rand_score(y_test, y_pred))
print("homogeneity_score", homogeneity_score(y_test, y_pred))
print("v_measure_score:", v_measure_score(y_test, y_pred))

adjusted_rand_score: 0.347475429348
homogeneity_score 0.523792125581
v_measure_score: 0.517122818967


## Principal Component Analysis (PCA)

In [18]:
from sklearn.decomposition import PCA
pca = PCA(n_components=0.95)
pca_model = pca.fit_transform(X_train)